name: Update README YouTube Thumbnails

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with latest YouTube videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26.1.0

      - name: Run Update Script
        run: node .github/scripts/update-youtube-thumbnails.js

      - name: Check for changes
        id: git-check
        run: |
          if git diff --quiet README.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push changes
        if: steps.git-check.outputs.changed == 'true'
        uses: test-room-7/action-update-file@v2
        with:
          file-path: README.md
          commit-msg: 'docs: update latest youtube episodes in README.md [skip ci]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
